### ISSUE TITLE
Directions for clang install on OSX, in case it's helpful

### ISSUE THREAD

**Issue by peteflorence** [JonathanRaiman/Dali#1]
Not an issue, just a comment in case it's helpfl

How to install correctly install clang on OSX

- Go to http://llvm.org/releases/download.html
- Under LLVM  3.6.0 (latest version as of May 2015), download "Clang for OSX" (tarball)
- Unpack .tar.xz (which will by default be in ~/Downloads)
- Then cd into clang and copy to /usr/local:

```
cd clang+llvm-3.6.0-x86_64-apple-darwin
cp -R ./* /usr/local/
```

**Comment by JonathanRaiman** [comment]
Thanks I'll move this to the readme asap

**Comment by nivwusquorum** [comment]
Readme updated. Thanks Pete!
