### ISSUE TITLE
No .deb for GPU

### ISSUE THREAD

**Issue by noe** [JonathanRaiman/Dali#9]
There is no .deb file in https://github.com/JonathanRaiman/Dali/releases for GPU.

Also, the instructions in README.md to install the GPU deb file under Ubuntu fail silently under this situation (the -q in the wget prevents the error message from appearing and the && before dpkg prevents it from executing; either removing the "q"  parameter in wget or having a "|| echo Error" just after the invocation to dpkg would make the error more evident).

Thanks for your efforts.

**Comment by nivwusquorum** [comment]
I missed that uninvited `-q`, thanks for pointing it out. I'll update it and the GPU version today afternoon/evening. Thanks for your patience.

**Comment by nivwusquorum** [comment]
Alright, I uploaded the GPU and removed `-q`. Are you running 64bit OS? I did not have chance to compile 32bit versions yet...

**Comment by noe** [comment]
I am running on 64bits, so that is perfect for me. Thank you so much for your prompt response!

**Comment by nivwusquorum** [comment]
My pleasure ;-)

btw. We are still perfecting our pre-built deployment, so we would really appreciate any feedback you have.
